version: '3.8'
services:
  api-catalogue:
    image: api-catalogue
    build:
      context: ./api-catalogue
      dockerfile: Dockerfile
    container_name: api-catalogue
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27042/mobalpa_catalogue
    volumes:
      - ./api-catalogue/target/mobalpa-0.0.1-SNAPSHOT.jar:/app/api-catalogue.jar
    networks:
      - mobalpa-network

  api-delivery:
    build:
      context: ./api-delivery
      dockerfile: Dockerfile
    container_name: api-delivery
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:8889/mobalpa_delivery?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mobalpa-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:8889/mobalpa?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      CATALOGUE_BASE_URL: http://api-catalogue:8081/api/catalogue/
      DELIVERY_BASE_URL: http://api-delivery:8082/api/delivery/
    depends_on:
      api-catalogue:
        condition: service_started
      api-delivery:
        condition: service_started
    networks:
      - mobalpa-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: angular_front
    ports:
      - "4200:4200"
    networks:
      - mobalpa-network

networks:
  mobalpa-network:
    driver: bridge

volumes:
  mongo-data: