const comments = [
    // Avis positifs
    "Un site parfait pour tout achat en ligne !",
    "Très satisfait du service, je recommande !",
    "Produit de qualité, livraison rapide.",
    "Service client réactif et à l'écoute.",
    "Livraison rapide, produit conforme !",
    "Très bon rapport qualité/prix.",
    "Je suis ravi de mon achat, merci !",
    "Qualité au rendez-vous, rien à redire.",
    "Je recommande vivement ce produit.",
    "Produit arrivé en parfait état.",
    "Site sérieux, commande facile.",
    "Très bon achat, je recommande.",
    "Produit conforme à la description.",
    "Très satisfait, merci pour tout !",
    "Bon produit, livraison impeccable.",
    "Le service est parfait, merci !",
    "Produit de très bonne qualité.",
    "Je suis très content de mon achat.",
    "Service rapide et efficace.",
    "Très bon produit, je suis content.",
    "Commande traitée rapidement.",
    "Produit bien emballé et protégé.",
    "Excellent service, merci !",
    "Je suis très satisfait de mon achat.",
    "Produit conforme et de qualité.",
    "Livraison dans les délais, parfait !",
    "Très bon produit, livraison rapide.",
    "Achat satisfaisant, merci beaucoup.",
    "Je recommande ce site sans hésiter.",
    "Bon service, produit impeccable.",
    
    // Avis négatifs
    "Produit reçu défectueux, très déçu.",
    "Service client inexistant, une honte !",
    "Qualité médiocre, je déconseille.",
    "Livraison très lente, inadmissible.",
    "Produit non conforme à la description.",
    "Impossible de joindre le service client.",
    "Très mauvaise expérience d'achat.",
    "Je ne recommanderai plus sur ce site.",
    "Produit endommagé à l'arrivée.",
    "Très déçu par la qualité du produit.",
    "Commande annulée sans explication.",
    "Erreur dans ma commande, déception.",
    "Service client peu réactif.",
    "Produit de piètre qualité, évitez.",
    "Problème de livraison non résolu.",
    "Support client inutile, très frustrant.",
    "Produit arrivé en mauvais état.",
    "Site peu fiable, je ne recommande pas.",
    "Grosse déception, service médiocre.",
    "Livraison incomplète, très déçu.",
    "Produit de mauvaise qualité, à fuir.",
    "Remboursement impossible, scandale !",
    "Article reçu ne fonctionne pas.",
    "Délais non respectés, très frustrant.",
    "Problèmes récurrents, à éviter.",
    "Service après-vente déplorable.",
    "Commande incorrecte, aucune aide.",
    "Très mauvaise qualité pour le prix.",
    "Produit défectueux, aucune solution.",
    "Expérience client décevante."
];

module.exports = comments;