name: Check Direct Push

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  check_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check actor
        id: check_actor
        run: |
          if [[ "${{ github.actor }}" != "twnguydev" && "${{ github.actor }}" != "RomainEpitech" ]]; then
            echo "Direct push to the main branch is not allowed. Please create a pull request."
            echo "Actor: ${{ github.actor }}"
            exit 1
          else
            echo "Push by allowed user: ${{ github.actor }}"
          fi