name: Commit Message Check

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  check_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message
        id: check_commit_message
        run: |
          pattern="^(feat|fix|docs|style|refactor|perf|test|chore|revert)(\\([a-zA-Z0-9_-]+\\))?: .+ #[0-9]+$"
          last_commit_message=$(git log -1 --pretty=format:"%s")

          if [[ ! "$last_commit_message" =~ $pattern ]]; then
            echo "Invalid commit message: '$last_commit_message'"
            echo "Commit messages must follow the pattern: <type>(<optional scope>): <description> <#ticket_id>"
            exit 1
          else
            echo "Commit message is valid: '$last_commit_message'"

      - name: Set commit status
        if: success()
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "state": "success",
              "context": "check_commit_messages",
              "description": "Commit message meets the requirements",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            https://api.github.com/repos/${{ github.repository }}/statuses/$COMMIT_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}