name: Check File Line Count

on: [push, pull_request]

jobs:
  check_lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for files with more than 500 lines
        run: |
          max_lines=500
          error=false
          for file in $(find . -type f \( -name "*.ts" -o -name "*.html" \)); do
            line_count=$(wc -l < "$file")
            if [ "$line_count" -gt "$max_lines" ]; then
              echo "$file has $line_count lines, which is more than the $max_lines lines allowed."
              error=true
            fi
          done
          if [ "$error" = true ]; then
            exit 1
          fi